# cordoplan-backend/docker-compose.yml

services:
  # ----------------------------------------------------
  # 1. Servicio de la Base de Datos MySQL
  # ----------------------------------------------------
  mysql_db:
    image: mysql:8.0
    container_name: cordoplan_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      # Asegura que el script de inicialización SQL se ejecute
      - ./init_db:/docker-entrypoint-initdb.d/
    restart: always

  # ----------------------------------------------------
  # 2. Servicio del Backend Node.js
  # ----------------------------------------------------
  cordoplan_api:
    build: . # Usa el Dockerfile en la raíz
    container_name: cordoplan_api
    command: npm start # Ejecuta src/app.js a través del script 'start'
    ports:
      # FIX: Se cambia a 0.0.0.0 para que sea accesible desde la red local (móvil)
      - "0.0.0.0:3000:3000"
    environment:
      DB_HOST: mysql_db # Host interno para Node.js
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      TZ: Europe/Madrid # O la zona horaria que desees usar
      DB_NAME: ${DB_NAME}
      PORT: ${PORT}
    volumes:
      # Mapeo para hot-reloading: sincroniza el código, pero aísla node_modules
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mysql_db
    restart: always

volumes:
  mysql_data:
